<?php
 //[STAMP] 196ed54d5c23d6d7f20e89c731f8f87d

namespace Mautic\ChannelBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
