<?php
 //[STAMP] 44883e5852f6f227dcaf7be1a52e57cb

namespace Mautic\PageBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
