<?php
 //[STAMP] 490d0ed26ba9cf2c311d694c332a52be

namespace Mautic\CampaignBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
