<?php
 //[STAMP] 29d34a66e608664017e1edfa84f52a53

namespace Mautic\CategoryBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
