<?php
 //[STAMP] 39b982da94ed3ef9162a06d3a1386eb3

namespace Mautic\EmailBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
