<?php
 //[STAMP] e496c65c643ea1cae2d99e7ef2fca0bb

namespace Mautic\UserBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
