<?php
 //[STAMP] 3a137acea6d649f2beb4e7b85e7e4992

namespace Mautic\QueueBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
