<?php
 //[STAMP] bd5c28f343e480115f972812fdc83a09

namespace Mautic\DynamicContentBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
