<?php
 //[STAMP] c6bcbf61f8204c2b913ca03ff21ace32

namespace Mautic\SmsBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
