<?php
 //[STAMP] ca9983902cad332e65e8c90e2688300f

namespace Mautic\PluginBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
