<?php
 //[STAMP] 7f57f4ec67ebbb2713f5873491a1377b

namespace Mautic\LeadBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
