<?php
 //[STAMP] 911009aec513db619fe18c14750f4413

namespace Mautic\WebhookBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
