<?php
 //[STAMP] b97d7208a3e09da878b3f4dd6102979f

namespace Mautic\ConfigBundle\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
